version: 0.0.3
config:
  project:
    name: 4mica-core-avs
    version: 0.1.0
    context: devnet
    project_uuid: b60c60af-c2e7-4bc2-9483-7e5e01ebe5ac
    telemetry_enabled: true
    templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
    templateVersion: v0.0.18
    templateLanguage: "go"
